[project]
name = "nys-design-optimisation-using-pysam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "cloudpickle==3.1.2",
    "contourpy==1.3.3",
    "cycler==0.12.1",
    "dagshub>=0.6.3",
    "fonttools==4.60.1",
    "kiwisolver==1.4.9",
    "matlabengine>=25.2.2",
    "matplotlib==3.10.7",
    "mlflow>=3.6.0",
    "nlopt==2.9.1",
    "nrel-pysam==7.1.0",
    "numpy==2.2.6",
    "packaging==25.0",
    "pandas==2.3.3",
    "pillow==12.0.0",
    "pygad==3.5.0",
    "pyparsing==3.2.5",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "scipy==1.16.3",
    "setuptools==80.9.0",
    "six==1.17.0",
    "tzdata==2025.2",
]
